### ISSUE TITLE
Phase segregations

### ISSUE THREAD

**Issue by Sush1090** [ClapeyronThermo/Clapeyron.jl#324]
Hello,
As if now the phases in Clapeyron are `:liquid`, `:vapour` and `:unkown`. We can compute this through `identify_phase`.  
This probably has a small inaccuracy  as there is no `:twophase` segregation or super critical segregation. 

With the new implementations of general flash, can it be possible to have this segregation?  So the fluid can be : `:liquid`, `:vapour` , `:twophase`, `supercritical_liquid` or `supercritical_gas`. 

So in other words finding a way to replace `:unkown` to a known phase category.  Something like `PhaseSI` in CoolProp. 

For now I am using a simple local function to do this using `bubble_temperature`, `dew_temperature` and `crit` something like this:

```julia
using Clapeyron
using Clapeyron:PH

function PhaseIdentification(model::EoSModel,p,h,z)
    Tcrit = crit_pure(model)[1]
    T = PH.temperature(model,p,h,z)
    if (T>=Tcrit)
        return :vapour
    end
    if (T< Tcrit)
        bt = bubble_temperature(model,p,z)[1]
        dt = dew_temperature(model,p,z)[1]
        if bt<= T <= dt
            return :twophase
        end
        if dt< T
            return :vapour
        end
        if bt> T
            return :liquid
        end
    end
end
```
```julia
model = cPR(["ethane"],idealmodel = ReidIdeal)
T = 300; p = 101325; z = [5.0]; h = enthalpy(model,p,T,z)
PhaseIdentification(model,p,h,z) # :vapour
```
Now this is not completely reliable as computation of bubble and dew temperature is not robust. Hence would it be possible with the new flash computation to get a functionality like this? 

Thank you

**Comment by longemen3000** [comment]
Seems like a good idea. Just to add some context on the current design.

the phase tags were initially introduced to select an initial point for the liquid and vapour branches for the volume calculation algorithm. after a while, we started adding solid phase models (that would require a phase tag) and by request, an `:stable` tag to pass to the volume solver (That performs an stability test). For a long time, we could do calculations just fine.

Independently, we implemented a phase identification function (([here](https://doi.org/10.1016/j.fluid.2010.12.001), defined as `Clapeyron.pip(model,V,T,z)`), this function identifies if a point in V-T-z space is a liquid (or liquid-like conditions in supercritical states) or a gas (or gas-like conditions in supercritical states). solving for pip(V,T,z) == 1 should give you a division line between those two states (there are various division lines, but the one used by pip does not require any iterative procedures). Just recently, we connected pip + phase tags to create the function `VT_identify_phase`. (added in 0.6.0, as a helper function for `MultiPhaseTPFlash` to detect in what branch is an specified phase) Note that this only detects if a bulk point is on the liquid or vapour branch of the EoS, it does not have any info about phase separation.

Now, there is this third, Related problem: we can identify if a bulk point, but not if that phase has an split. The correct way to do this is by using the tangent phase stability criterion (`Clapeyron.tpd`). That is what `MultiPhaseTPFlash` uses on each phase to decide if add new phases or not). the TPD algorithm solves nc optimization problems and if all of those fail to converge, we can be (almost) sure that the point is in a single phase state. bubble and dew points are just looking at the temperature or pressure were `tpd(model,p,T,z) == 0` ([this paper ](https://doi.org/10.1016/j.fluid.2019.112242) implements a robust algorithm for solving those bubble points with a tpd basis.

For a robust phase identification algorithm, what we need is a `xy_tpd` function, that performs tpd with arbitrary phase specifications. there are some recent papers that implement unified formulation, I have to check those out. This would be the ideal state to have (and i don't really know if there any implementations out there for this haha).

now, with all this in mind, one way to implement `ph_identify_phase` would be:
```julia
function ph_identify_phase(model,p,h,z)
  res = ph_flash(model,p,h,z)
  Clapeyron.numphases(res) > 1 && return :equilibria
  v,T = res.volumes[1]*sum(z), Clapeyron.temperature(res)
  phase = VT_identify_phase(model,v,T,z) #identify if we are in a liquid or vapour branch
  is_sc = isnan(spinodal_pressure(model,T,z,v0 = v0)[1]) #if there is no stability limit, we suppose supercritical state
  if is_sc && Clapeyron.is_vapour(phase)
    return :supercritical_vapour
  elseif is_sc && Clapeyron.is_liquid(phase)
    return :supercritical_liquid
  else
    return phase
  end
end
```

**Comment by longemen3000** [comment]
`ph_flash` depends at the end on the stability of `dew_temperature` and `bubble_temperature`, so an initialization point based on tpd would be a net improvement

**Comment by Sush1090** [comment]
Thank you for this information. I will look into this. 
There still exists the question of state point being in the two-phase region. If we rely only on `VT_identify_phase` then it will return 
`:liquid` or `:gas` depending on which is the stable node. 

But possibly with the help of `qp_flash` or other method (`tpd`) it seems possible.

**Comment by longemen3000** [comment]
Yeah, the only way to be absolutely sure Is to perform a tpd on that specific point.

**Comment by longemen3000** [comment]
just to add to the conversation, this is the order of tests that one should be doing, in order of evaluation costs
- dpdv > 0: complete instability in pure and multicomponent mixtures (cost: 1 V-T evaluation)
- `VT_diffusive_stability(model,V,T,z) == false`: equivalent to dpdv in the single component phase, more strict than dpdv in multicomponent case. (cost: 1 hessian of a V-T-z evaluation + 1 eigen calculation)
- tpd:  should determine if there is any phase split on any phase (cost: 1 global optimization on the entire [0,1]^np space)

**Comment by longemen3000** [comment]
Hmm, I will have to check,  probably a bug

**Comment by longemen3000** [comment]
found the bug, it was unconditionally returning true for single component models. i'm trying to diagnose some weird NaN that appears while calculating this, but in the meanwhile, this function is the fixed version
```
using LinearAlgebra
function my_diffusive_stability(model,V,T,z = SA[1.0])
    ρᵢ = z ./ V
    HΨ = Clapeyron.Ψ_hessian(model,T,ρᵢ) #isochoric formalism
    if any(!isfinite,HΨ)
        return zero(eltype(HΨ))/zero(eltype(HΨ)) #i'm looking at the moment why this fails sometimes and what to do here.
    end
    λ = eigmin(Hermitian(HΨ)) # calculating just minimum eigenvalue more efficient than calculating all & finding min
    return λ
end

Vv = collect(range(4.1e-5,0.2,1000)); #lb_volume(model) = 4.04e-5
stability= VT_diffusive_stability.(model,Vv,T,Ref(z))
```
that should return:
```
julia> stability= VT_diffusive_stability.(model,Vv,T,Ref(z))
1000-element Vector{Float64}:
 NaN
   2.154490295904884
  -0.29254381195594525
  -0.42522417473280016
  -0.4754611539894807
  -0.49407506046307936
   ⋮
  59.69433615194667
  59.75569778045417
  59.817059418498005
  59.87842106604963
  59.939782723080604
```
the thing that i'm trying to diagnose is that NaN value at the start

**Comment by Sush1090** [comment]
Hello @longemen3000 ,
~~I have a question on this, is it not possible to do a simple phase segregation using bubble, dew, crit and the flashes that are already implemented?~~ 

~~Or going through `tpd` is necessary?~~


Edit Never mind, I found my answer. we need tpd
